### ISSUE TITLE
Mirror not working on 1.9.68

### ISSUE THREAD

**Issue by mattanddesign** [koenbok/Framer#166]
Worked great until the latest update. Now I just get the following output:

````
Traceback (most recent call last):
  File "/Applications/Framer Studio.app/Contents/Resources/python/vendor/packages.zip/tornado/web.py", line 1334, in _execute
    result = yield result
  File "/Applications/Framer Studio.app/Contents/Resources/python/vendor/packages.zip/tornado/gen.py", line 628, in run
    value = future.result()
  File "/Applications/Framer Studio.app/Contents/Resources/python/vendor/packages.zip/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/Applications/Framer Studio.app/Contents/Resources/python/vendor/packages.zip/tornado/gen.py", line 175, in wrapper
    yielded = next(result)
  File "/Applications/Framer Studio.app/Contents/Resources/python/vendor/packages.zip/tornado/web.py", line 2110, in get
    self.root, absolute_path)
  File "/Applications/Framer Studio.app/Contents/Resources/python/reloader/server.py", line 154, in validate_absolute_path
    raise HTTPError(403, "%s is not in current user directory", absolute_path)
HTTPError: HTTP 403: Forbidden (/Applications/Framer Studio.app/Contents/Resources/python/reloader/www/app is not in current user directory)
````
A somewhat related issue, the url in the dialog box is missing too…

![screen shot 2015-01-21 at 4 48 17 pm](https://cloud.githubusercontent.com/assets/1939892/5831781/7fe48bc8-a18d-11e4-9419-2cd7881dc70a.png)

**Comment by koenbok** [comment]
Hey @mattanddesign I figured out what happens here and fixed it. It will be included in the next release.

**Comment by mattanddesign** [comment]
Awesome thanks!
