### ISSUE TITLE
Framer Studio - Can't include modules

### ISSUE THREAD

**Issue by jchavarri** [koenbok/Framer#284]
While trying to use modules on Framer Studio, I'm getting an error. Even when using the default `myModule` module that is prebundled with every .framer project.

Even if the console log included below shows that `coffeeify` is missing, I'm pretty sure I've seen `browserify-shim` missing in other cases as well.

Version: v47
Build: 2665

Console log:
```
Error: Module myModule can't be found
Error: Cannot find module 'coffeeify' from '/Users/javi/Downloads'
  at /Applications/Framer Studio.app/Contents/Resources/FramerModuleBuilder/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
  at process (/Applications/Framer Studio.app/Contents/Resources/FramerModuleBuilder/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
  at ondir (/Applications/Framer Studio.app/Contents/Resources/FramerModuleBuilder/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
  at load (/Applications/Framer Studio.app/Contents/Resources/FramerModuleBuilder/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
  at onex (/Applications/Framer Studio.app/Contents/Resources/FramerModuleBuilder/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
  at /Applications/Framer Studio.app/Contents/Resources/FramerModuleBuilder/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:82:15)
(anonymous function).temp.html:1
```

**Comment by jchavarri** [comment]
I just tried again (with the same Framer Studio instance) and it works. I didn't even need to restart Framer Studio, so my guess is that I was having problems due to some caching, as I was using an html file that pointed to a custom Framer version just before this error arose yesterday. Closing.

**Comment by jornvandijk** [comment]
Thanks for reporting anyway!
